### ISSUE TITLE
Decisions to be taken

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/t3docs-wiki-migration#19]
The following decisions are related to the wiki migration and should be re-checked:

- [x] https://decisions.typo3.org/t/deletion-criteria-for-the-wiki/585/2
- [ ] https://decisions.typo3.org/t/maintain-documentation-for-old-typo3-versions-before/584/8
- [x] https://decisions.typo3.org/t/documentation-content-what-to-do-about-the-wiki-revisited/583/8

**Comment by sypets** [comment]
I propose to leave a short comment in the decisions summarizing the status quo.

@alexander-nitsche Please have a look and if you would change anything (decision 1 and 3 have the same comment): https://decisions.typo3.org/t/deletion-criteria-for-the-wiki/585/2?u=sypets

I can still edit the comment if necessary.

**Comment by sypets** [comment]
About the deletion criteria - that might still be a good idea to decide something but the decision is a monster with lots of comments. I need some time to read this ....

@alexander-nitsche If you or anyone has a good idea on this or something has already been decided, please hit me on Slack and I can update it.

**Comment by alexander-nitsche** [comment]
The comments for decisions (1) and (3) are fine from my point of view. Will leave a comment in the decision (2).

**Comment by linawolf** [comment]
Project is archvied
